name: Run tests and attach Allure report as html file

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Compile binaries
        run: mvn compile

  automation:
    name: "Automation"
    runs-on: ubuntu-latest
    needs: [ "build" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set-up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 11
      - name: Download Allure
        run: |
          wget -O allure-2.29.0.tgz -q https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz
          tar -zxvf allure-2.29.0.tgz -C /opt/
          echo "PATH=$PATH:/opt/allure-2.29.0/bin" >> $GITHUB_ENV
      - name: Run automation tests
        run: mvn test
      - name: Generate Allure report
        run: allure generate --single-file allure-results
      - name: Upload Allure report
        uses: actions/upload-artifact@v2
        with:
          name: Allure report
          path: allure-report/index.html
